name: recipes
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.1.1
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_riverpod: ^2.3.3
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.3
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.5
  riverpod_lint: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/recipe-book.png

